import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react'

export default function Home() {
  const [darkMode,setDarkMode] = useState(false);
  return (
    <div  className={darkMode?"dark":""}>
      <Head>
        <title>Dheeraj Sharma Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gradient-to-r from-gray-700 to-slate-300" >
           <section className="min-h-screen">
             <nav className="py-10 mb-12 justify-between flex ">
              <h1 className="text-xl font-burtons">Devlopedbyds</h1>
              <ul className="flex items-center">
                <li>
                    <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
                </li>
                <li>
                  <a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
                </li>
              </ul>
             </nav>

             <div className="text-center p-10">
                <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Dheeraj Sharma</h2>
                <h3 className='text-2xl py-2 md:text-3xl'>Web Developer</h3>
                <p className='text-md leading-8 py-5 text-gray-800 md:text-xl max-w-xl mx-auto'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?

                Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?

                Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis? 
                </p>
             </div>

             <div className='text-5xl flex gap-16 justify-center text-gray-500 py-3'>
              <AiFillTwitterCircle/>
              <AiFillLinkedin/>
              <AiFillYoutube/>
             </div>

             <div className='bg-gradient-to-b mx-auto from-teal-500 relative rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 '>
                  <Image src={deved} layout='fill' objectFit='content'/>
             </div>
           </section>

           <section>
              <div>
                <h3 className='text-3xl py-1'>Services I Offer</h3>
            <p className='text-md leading-8 py-5 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde,<span className='text-teal-500'>  amet consectetur</span> laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur<span className='text-teal-500'>  amet consectetur</span> laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet<span className='text-teal-500'>  amet consectetur</span> ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis
             </p>

             <p className='text-md leading-8 py-5 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?
              Lorem ipsum dolor sit <span className='text-teal-500'>  amet consectetur</span> adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?
              Lorem ipsum dolor sit <span className='text-teal-500'>  amet consectetur</span> amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae <span className='text-teal-500'>  amet consectetur</span> consequuntur ut eveniet asperiores dicta explicabo quis
             </p>
              </div>

              <div className='lg:flex gap-10'>
                <div className='text-center shadow-lg p-10 rounded-xl my-10 '>
                  <Image className='mx-auto' src={design} width={100} height={100} />
                  <h3 className='text-lg font-medium pt-8 pb-2 '>Eye catching design</h3>
                  <p className='py-2'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum hic corporis rerum quos perspiciatis natus reprehenderit quod rem ut eum? Voluptatibus recusandae ratione ducimus adipisci dolores quasi impedit ex unde!</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                  <p className='text-gray-800 py-1'>PhotoShop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
                </div>

                <div className='text-center shadow-lg p-10 rounded-xl my-10 '>
                  <Image className='mx-auto' src={consulting} width={100} height={100} />
                  <h3 className='text-lg font-medium pt-8 pb-2 '>Eye catching design</h3>
                  <p className='py-2'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum hic corporis rerum quos perspiciatis natus reprehenderit quod rem ut eum? Voluptatibus recusandae ratione ducimus adipisci dolores quasi impedit ex unde!</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                  <p className='text-gray-800 py-1'>PhotoShop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
                </div>

                <div className='text-center shadow-lg p-10 rounded-xl my-10 '>
                  <Image className='mx-auto' src={code} width={100} height={100} />
                  <h3 className='text-lg font-medium pt-8 pb-2 '>Eye catching design</h3>
                  <p className='py-2'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum hic corporis rerum quos perspiciatis natus reprehenderit quod rem ut eum? Voluptatibus recusandae ratione ducimus adipisci dolores quasi impedit ex unde!</p>
                  <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                  <p className='text-gray-800 py-1'>PhotoShop</p>
                  <p className='text-gray-800 py-1'>Illustrator</p>
                  <p className='text-gray-800 py-1'>Figma</p>
                </div>
              </div>
           </section>

           <section>
              <div>
            <h3 className='text-3xl py-1'>
              Portfolio 
            </h3>
            <p className='text-md leading-8 py-5 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?
              Lorem ipsum dolor sit <span className='text-teal-500'>  amet consectetur</span> adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae consequuntur ut eveniet asperiores dicta explicabo quis?
              Lorem ipsum dolor sit <span className='text-teal-500'>  amet consectetur</span> amet consectetur adipisicing elit. Adipisci amet ipsum voluptatum consequuntur laborum? Debitis quod unde, laudantium rem quae soluta odio molestiae <span className='text-teal-500'>  amet consectetur</span> consequuntur ut eveniet asperiores dicta explicabo quis
            </p>
          </div>

          <div className='flex flex-col  gap-10 py-10 md:flex-row lg:flex-wrap'>
             <div className='basis-1/3 py-10 flex-1'><Image className='rounded-lg object-cover' src={web1} width={"100%"} height={"100%"} layout="responsive"/><div/>
             <div className='basis-1/3 py-10 flex-1'><Image className='rounded-lg object-cover' src={web2} width={"100%"} height={"100%"} layout="responsive"/></div>
             <div className='basis-1/3 py-10 flex-1'><Image className='rounded-lg object-cover' src={web3} width={"100%"} height={"100%"} layout="responsive"/></div>
             <div className='basis-1/3 py-10 flex-1'><Image className='rounded-lg object-cover' src={web4} width={"100%"} height={"100%"} layout="responsive"/></div> 
             <div className='basis-1/3 py-10 flex-1'><Image className='rounded-lg object-cover' src={web5} width={"100%"} height={"100%"} layout="responsive"/></div>
             <div className='basis-1/3 py-10 flex-1'><Image className='rounded-lg object-cover' src={web6} width={"100%"} height={"100%"} layout="responsive"/></div>    
             </div>
          </div>
           </section>
      </main>

    </div>
  )
}
